### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by TeslaOwnerTips** [meg768/homebridge-my-tesla#16]
TypeError: Cannot read properties of undefined (reading 'find')
    at TeslaAPI.getVehicle (/opt/homebrew/lib/node_modules/homebridge-my-tesla/src/tesla-api-request.js:285:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Vehicle.getAccessories (/opt/homebrew/lib/node_modules/homebridge-my-tesla/src/vehicle.js:60:17)

No accessories shown :(
I double checked the refresh token and VIN

  {
            "platform": "Tesla",
            "name": "My Tesla Plugin",
            "vehicles": [
                {
                    "name": "TeslaMy",
                    "vin": "xx",
                    "token": "xx",
                    "expose": [
                        "ping",
                        "defrost",
                        "ventilation",
                        "trunk",
                        "hvac",
                        "doors",
                        "insideTemperature",
                        "steeringWheelHeater"
                    ],
                    "accessories": {
                        "ping": {
                            "name": "Keep Tesla Awake",
                            "requiredBatteryLevel": 50,
                            "timerInterval": 1
                        },
                        "defrost": {
                            "name": "Defrost Tesla"
                        },
                        "ventilation": {
                            "name": "Teslas Ventilation"
                        },
                        "trunk": {
                            "name": "Open Teslas Trunk"
                        },
                        "charging": {
                            "name": "Teslas Charger"
                        },
                        "hvac": {
                            "name": "Teslas Climate",
                            "requiredBatteryLevel": 20
                        },
                        "doors": {
                            "name": "Doors",
                            "remoteStartDrivePassword": ""
                        },
                        "outsideTemperature": {
                            "name": "Temperature Outside Tesla"
                        },
                        "insideTemperature": {
                            "name": "Temperature Inside Tesla"
                        },
                        "thermostat": {
                            "name": "Set Teslas Temperature",
                            "requiredBatteryLevel": 40,
                            "timerInterval": 2
                        },
                        "steeringWheelHeater": {
                            "name": "Steering Wheel Heater"
                        }
                    }
                }

**Comment by meg768** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/4264015/147290896-011767ed-4353-4c55-8201-3c785f88e203.png">

Looks like the response was not an array witch it should be. Hmm.

**Comment by meg768** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/4264015/147291738-a44e9b7e-cfb2-4580-b7f6-2d58a5852ce5.png">

I don't think it has anything to do with VIN or the refresh token. Try setting debug to true.

**Comment by TeslaOwnerTips** [comment]
[12/23/2021, 4:34:00 PM] Homebridge v1.3.8 (HAP v0.9.7) (Tesla) is running on port 51953.
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Launched child bridge with PID 30768
[12/23/2021, 4:34:00 PM] Registering platform 'homebridge-my-tesla.Tesla'
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Loaded homebridge-my-tesla v1.0.91 child bridge successfully
[12/23/2021, 4:34:00 PM] Loaded 0 cached accessories from cachedAccessories.0EC81E8AF154.
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Creating accessories...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory doors...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory doors...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory charging...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory hvac...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory hvac...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory ping...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory ping...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory insideTemperature...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory insideTemperature...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory outsideTemperature...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory trunk...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory trunk...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory defrost...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory defrost...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory steeringWheelHeater...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory steeringWheelHeater...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Searching for accessory ventilation...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Exposing accessory ventilation...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] No access token or too long since access token was generated.
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] Fetching new access token...
[12/23/2021, 4:34:00 PM] [My Tesla Plugin] This access token will expire Invalid Date.
[12/23/2021, 4:34:01 PM] [My Tesla Plugin] TypeError: Cannot read properties of undefined (reading 'find')
    at TeslaAPI.getVehicle (/opt/homebrew/lib/node_modules/homebridge-my-tesla/src/tesla-api-request.js:285:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Vehicle.getAccessories (/opt/homebrew/lib/node_modules/homebridge-my-tesla/src/vehicle.js:60:17)
[12/23/2021, 4:34:01 PM] Publishing bridge accessory (name: My Tesla 922-00-922, publishInfo: {
  username: '0E:C8:1E:8A:F1:54',
  port: 34935,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[12/23/2021, 4:34:01 PM] [My Tesla Plugin] Finished launching.
[12/23/2021, 4:34:01 PM] Homebridge v1.3.8 (HAP v0.9.7) (My Tesla 922-00-922) is running on port 34935.

**Comment by TeslaOwnerTips** [comment]
"platform": "Tesla",
            "name": "My Tesla Plugin",
            "debug": true,
            "vehicles": [
                {
                    "name": "TeslaMy",

**Comment by meg768** [comment]
Maybe it is the refresh token? I use the app "Auth for Tesla" to give me a refresh token.

**Comment by meg768** [comment]
Anyhow, the code should throw errors when not receiving what it expects.

**Comment by meg768** [comment]
Published a new version 1.0.92 on npm. It logs a bit more if something fails.

**Comment by TeslaOwnerTips** [comment]
Turns out I had the wrong refresh token.
Tesla Fi has the old "Refresh Token:" and a newer "SSO Refresh Token:". Its the SSO version that I needed. Its massive.
